platform :ios, '8.0'
target 'kehuiyan' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'RegexKitLite', '~> 4.0'
    pod 'SDCycleScrollView', '~> 1.65'
    pod 'KLCPopup', '~> 1.0'
    pod 'XHToast', '~> 1.3.0'
    pod 'XHLaunchAd'
    pod 'JPush', '~> 3.0.7'
    pod 'zhPopupController', '~> 1.0.2'
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'IQKeyboardManager'
end
